version: "3.9"
name: application
services:
  database:
    image: postgres:17 # Use a specific, recent Postgres image version
    container_name: postgres
    environment:
      POSTGRES_USER: kern
      POSTGRES_PASSWORD: kern
      POSTGRES_DB: kern_iam # Optional: creates a default database on startup
    ports:
      # Maps port 5432 on your host to port 5432 in the container
      - "5432:5432"
    networks:
      - back-end

  kern-iam-node:
    image: kern-iam:1.0-SNAPSHOT
    ports:
      - "8080-8082:8080"
    networks:
      - back-end
    depends_on:
      - database
    deploy:
      mode: replicated
      replicas: 3
networks:
  back-end:
    driver: bridge