server:
  port: 8080
  error:
    include-binding-errors: ALWAYS
    include-message: ALWAYS
    include-stacktrace: ALWAYS
    include-exception: true

spring:
  main:
    banner-mode: off
  web:
    locale: en_US
  application:
    name: kern-iam
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PWD}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  liquibase:
    enabled: true
    change-log: /db/liquibase/scripts/master.yml
    drop-first: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.zaxxer.hikari: WARN
    org.springframework.jdbc: WARN
    org.springframework.boot.autoconfigure.jdbc: WARNk