server:
  port: 8080
  error:
    include-binding-errors: ALWAYS
    include-message: ALWAYS
    include-stacktrace: ALWAYS
    include-exception: true

spring:
  main:
    banner-mode: off
  web:
    locale: en_US
  application:
    name: kern-iam
  datasource:
    url: jdbc:postgresql://localhost:5432/kern_iam
    username: kern
    password: kern
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  liquibase:
    enabled: true
    change-log: /db/liquibase/scripts/master.yml
    drop-first: false